
apiVersion: v1
kind: Secret
metadata:
  name: nginx-secret
type: Opaque
data:
  username: YWRtaW4=        # "admin"
  password: cGFzc3dvcmQxMjM= # "password123"
  password5: cGFzc3dvcmQxMjM= # "password123"
  token: dGVzdC10b2tlbg==   # "test-token"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            # test
        }
    }
  default5.conf: |
    server {
        listen 81;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            # test
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
spec:
  # 调度到虚拟节点（替换为你的 VK_NODE_NAME）
  nodeName: ssh-node-192-168-1-201

  tolerations:
    - key: "virtual-kubelet.io/provider"
      operator: "Equal"
      value: "ssh-compose"
      effect: "NoSchedule"

  containers:
    - name: nginx
      image: m.daocloud.io/docker.io/library/nginx:latest
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        limits:
          cpu: "0.5"
          memory: "512Mi"
      volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: config2
          mountPath: /tmp/config
        - name: config3
          mountPath: /tmp/config3/default.conf
          subPath: default.conf
        - name: secret
          mountPath: /etc/secret
        - name: cache
          mountPath: /tmp/cache
        - name: data
          mountPath: /data

    - name: blog
      image: m.daocloud.io/docker.io/library/busybox:latest
      command:
        - sh
        - -c
        - |
          FOO=hello
          echo "${FOO} ${BAR:-world}"
      volumeMounts:
        - name: data
          mountPath: /data

  volumes:
    - name: config
      configMap:
        name: nginx-config
        items:
          - key: default.conf
            path: site.conf
    - name: config2
      configMap:
        name: nginx-config
    - name: config3
      configMap:
        name: nginx-config
    - name: secret
      secret:
        secretName: nginx-secret
    - name: cache
      emptyDir: {}
    - name: data
      hostPath:
        path: /tmp/data/
        type: DirectoryOrCreate # 如果宿主机目录不存在会自动创建，按需保留或改为 Directory
